// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class Conflict extends BaseHTTPError {
  statusCode = 409;

  title = 'Conflict';

  constructor(detail: string = '') {
    super(detail);
  }
}
