// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class InternalServerError extends BaseHTTPError {
  statusCode = 500;

  title = 'Internal Server Error';

  constructor(detail: string = '') {
    super(detail);
  }
}
