// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class MisdirectedRequest extends BaseHTTPError {
  statusCode = 421;

  title = 'Misdirected Request';

  constructor(detail: string = '') {
    super(detail);
  }
}
