// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class NotAcceptable extends BaseHTTPError {
  statusCode = 406;

  title = 'Not Acceptable';

  constructor(detail: string = '') {
    super(detail);
  }
}
