// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class NotImplemented extends BaseHTTPError {
  statusCode = 501;

  title = 'Not Implemented';

  constructor(detail: string = '') {
    super(detail);
  }
}
