// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class RequestTimeout extends BaseHTTPError {
  statusCode = 408;

  title = 'Request Timeout';

  constructor(detail: string = '') {
    super(detail);
  }
}
