// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class UnavailableForLegalReasons extends BaseHTTPError {
  statusCode = 451;

  title = 'Unavailable For Legal Reasons';

  constructor(detail: string = '') {
    super(detail);
  }
}
