// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class UpgradeRequired extends BaseHTTPError {
  statusCode = 426;

  title = 'Upgrade Required';

  constructor(detail: string = '') {
    super(detail);
  }
}
