// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class UriTooLong extends BaseHTTPError {
  statusCode = 414;

  title = 'URI Too Long';

  constructor(detail: string = '') {
    super(detail);
  }
}
