// This file was generated by liblab | https://liblab.com/ | https://liblab.com

import { BaseHTTPError } from './base';

export default class VariantAlsoNegotiates extends BaseHTTPError {
  statusCode = 506;

  title = 'Variant Also Negotiates';

  constructor(detail: string = '') {
    super(detail);
  }
}
