// This file was generated by liblab | https://liblab.com/ | https://liblab.com

export type { Error } from './models/Error';
export type { Pet } from './models/Pet';
export type { Pets } from './models/Pets';
