// This file was generated by liblab | https://liblab.com/ | https://liblab.com

export type  { Error } from './services/pets/models/Error';
export type  { Pet } from './services/pets/models/Pet';
export type  { Pets } from './services/pets/models/Pets';
